--- #YAML:1.0
name:                Pod-Server
version:             1.06
abstract:            a web server for locally installed perl documentation
license:             mit
author:              
    - John BEPPU <beppu@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Which:                   0
    HTML::AsSubs:                  0
    Pod::Simple::HTML:             0
    Squatting:                     0.5
    Text::VimColor:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
